# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f436e66de127fb6abf6ad7252dd0a23e42c1820b0b9bfb2e146186d0e309381dc381add5a2f48cb087785b70643a8aaeedca04ed86d2bdc8147cd38905a4aca4

test:
  secret_key_base: c80a6969f8d479489ca02501f843ff3ff7933128b8a435242cbf1381f99b6ffdabe381169bb4e8a8b23ecabd64fdd8cb90d174d47a2e46e523b37d7c2c71bf3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
